name: Build FFmpeg

on:
  push:

jobs:
  purge_artifacts:
    name: Purge old artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Purge old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: 0 days
          skip-recent: 3
  build_ffmpeg:
    name: Build ffmpeg
    needs: build_targets
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [win32]
        variant: [gpl-shared,lgpl-shared]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build ffmpeg
        run: ./build.sh ${{ matrix.target }} ${{ matrix.variant }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg
          path: artifacts/*
